DROP DATABASE IF EXISTS `screening`;
CREATE DATABASE IF NOT EXISTS `screening` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `screening`;

DROP TABLE IF EXISTS `screening`;
CREATE TABLE IF NOT EXISTS `screening` (
    `screening_id` INT AUTO_INCREMENT PRIMARY KEY,
    `movie_name` VARCHAR(255) NOT NULL,
    `movie_description` TEXT NOT NULL,
    `movie_date_time` DATETIME NOT NULL,
    `location` VARCHAR(255) NOT NULL,
    `movie_status` ENUM('active', 'cancelled') NOT NULL DEFAULT 'active',
    `ticket_price` DECIMAL(10, 2) NOT NULL,
    `capacity` INT NOT NULL,
    `hall_number` INT NOT NULL,
    `creation_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `seat`;
CREATE TABLE IF NOT EXISTS `seat` (
    `screening_id` INT NOT NULL,
    `seat_id` INT NOT NULL,
    `seat_status` ENUM('available', 'booked', 'reserved', 'unavailable') NOT NULL DEFAULT 'available',
    PRIMARY KEY (`screening_id`, `seat_id`),
    FOREIGN KEY (`screening_id`) REFERENCES `screening` (`screening_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `screening` (`movie_name`, `movie_description`, `movie_date_time`, `movie_status`, `ticket_price`, `capacity`, `hall_number`) VALUES
('Avatar: The Way of Water', 'Embark on a breathtaking journey to the depths of Pandora as you explore the wonders of the underwater world in this highly anticipated sequel to James Camerons epic saga.', '2024-05-05 18:00:00', 'Showing', 15.00, 50, 1),
('Ant-Man and the Wasp: Quantumania', 'Prepare for a mind-bending adventure through the quantum realm as Ant-Man and the Wasp team up once again to thwart new threats and unravel the mysteries of time and space.', '2024-05-04 20:00:00', 'Showing', 15.00, 50, 2),
('Everything Everywhere All At Once', 'Experience an exhilarating odyssey across infinite dimensions in this genre-bending masterpiece that defies all expectations and pushes the boundaries of storytelling.', '2024-05-05 14:00:00', 'Showing', 15.00, 50, 3),
('Elvis', 'Step into the spotlight and witness the rise of a legend as Elvis Presley takes the stage in this electrifying biopic that celebrates the life, music, and legacy of the King of Rock \'n\' Roll.', '2024-05-06 20:00:00', 'Showing', 15.00, 50, 4);


INSERT INTO `seat` (`screening_id`, `seat_id`, `seat_status`) VALUES
(1, 1, 'available'),
(1, 2, 'available'),
(1, 3, 'available'),
(1, 4, 'available'),
(1, 5, 'available'),
(1, 6, 'available'),
(1, 7, 'available'),
(1, 8, 'available'),
(1, 9, 'available'),
(1, 10, 'available'),
(1, 11, 'available'),
(1, 12, 'available'),
(1, 13, 'available'),
(1, 14, 'available'),
(1, 15, 'available'),
(1, 16, 'available'),
(1, 17, 'available'),
(1, 18, 'available'),
(1, 19, 'available'),
(1, 20, 'available'),
(1, 21, 'available'),
(1, 22, 'available'),
(1, 23, 'available'),
(1, 24, 'available'),
(1, 25, 'available'),
(1, 26, 'available'),
(1, 27, 'available'),
(1, 28, 'available'),
(1, 29, 'available'),
(1, 30, 'available'),
(1, 31, 'available'),
(1, 32, 'available'),
(1, 33, 'available'),
(1, 34, 'available'),
(1, 35, 'available'),
(1, 36, 'available'),
(1, 37, 'available'),
(1, 38, 'available'),
(1, 39, 'available'),
(1, 40, 'available'),
(1, 41, 'available'),
(1, 42, 'available'),
(1, 43, 'available'),
(1, 44, 'available'),
(1, 45, 'available'),
(1, 46, 'available'),
(1, 47, 'available'),
(1, 48, 'available'),
(1, 49, 'available'),
(1, 50, 'available'),
(2, 1, 'available'),
(2, 2, 'available'),
(2, 3, 'available'),
(2, 4, 'available'),
(2, 5, 'available'),
(2, 6, 'available'),
(2, 7, 'available'),
(2, 8, 'available'),
(2, 9, 'available'),
(2, 10, 'available'),
(2, 11, 'available'),
(2, 12, 'available'),
(2, 13, 'available'),
(2, 14, 'available'),
(2, 15, 'available'),
(2, 16, 'available'),
(2, 17, 'available'),
(2, 18, 'available'),
(2, 19, 'available'),
(2, 20, 'available'),
(2, 21, 'available'),
(2, 22, 'available'),
(2, 23, 'available'),
(2, 24, 'available'),
(2, 25, 'available'),
(2, 26, 'available'),
(2, 27, 'available'),
(2, 28, 'available'),
(2, 29, 'available'),
(2, 30, 'available'),
(2, 31, 'available'),
(2, 32, 'available'),
(2, 33, 'available'),
(2, 34, 'available'),
(2, 35, 'available'),
(2, 36, 'available'),
(2, 37, 'available'),
(2, 38, 'available'),
(2, 39, 'available'),
(2, 40, 'available'),
(2, 41, 'available'),
(2, 42, 'available'),
(2, 43, 'available'),
(2, 44, 'available'),
(2, 45, 'available'),
(2, 46, 'available'),
(2, 47, 'available'),
(2, 48, 'available'),
(2, 49, 'available'),
(2, 50, 'available'),
(3, 1, 'available'),
(3, 2, 'available'),
(3, 3, 'available'),
(3, 4, 'available'),
(3, 5, 'available'),
(3, 6, 'available'),
(3, 7, 'available'),
(3, 8, 'available'),
(3, 9, 'available'),
(3, 10, 'available'),
(3, 11, 'available'),
(3, 12, 'available'),
(3, 13, 'available'),
(3, 14, 'available'),
(3, 15, 'available'),
(3, 16, 'available'),
(3, 17, 'available'),
(3, 18, 'available'),
(3, 19, 'available'),
(3, 20, 'available'),
(3, 21, 'available'),
(3, 22, 'available'),
(3, 23, 'available'),
(3, 24, 'available'),
(3, 25, 'available'),
(3, 26, 'available'),
(3, 27, 'available'),
(3, 28, 'available'),
(3, 29, 'available'),
(3, 30, 'available'),
(3, 31, 'available'),
(3, 32, 'available'),
(3, 33, 'available'),
(3, 34, 'available'),
(3, 35, 'available'),
(3, 36, 'available'),
(3, 37, 'available'),
(3, 38, 'available'),
(3, 39, 'available'),
(3, 40, 'available'),
(3, 41, 'available'),
(3, 42, 'available'),
(3, 43, 'available'),
(3, 44, 'available'),
(3, 45, 'available'),
(3, 46, 'available'),
(3, 47, 'available'),
(3, 48, 'available'),
(3, 49, 'available'),
(3, 50, 'available'),
(4, 1, 'available'),
(4, 2, 'available'),
(4, 3, 'available'),
(4, 4, 'available'),
(4, 5, 'available'),
(4, 6, 'available'),
(4, 7, 'available'),
(4, 8, 'available'),
(4, 9, 'available'),
(4, 10, 'available'),
(4, 11, 'available'),
(4, 12, 'available'),
(4, 13, 'available'),
(4, 14, 'available'),
(4, 15, 'available'),
(4, 16, 'available'),
(4, 17, 'available'),
(4, 18, 'available'),
(4, 19, 'available'),
(4, 20, 'available'),
(4, 21, 'available'),
(4, 22, 'available'),
(4, 23, 'available'),
(4, 24, 'available'),
(4, 25, 'available'),
(4, 26, 'available'),
(4, 27, 'available'),
(4, 28, 'available'),
(4, 29, 'available'),
(4, 30, 'available'),
(4, 31, 'available'),
(4, 32, 'available'),
(4, 33, 'available'),
(4, 34, 'available'),
(4, 35, 'available'),
(4, 36, 'available'),
(4, 37, 'available'),
(4, 38, 'available'),
(4, 39, 'available'),
(4, 40, 'available'),
(4, 41, 'available'),
(4, 42, 'available'),
(4, 43, 'available'),
(4, 44, 'available'),
(4, 45, 'available'),
(4, 46, 'available'),
(4, 47, 'available'),
(4, 48, 'available'),
(4, 49, 'available'),
(4, 50, 'available');